/* Auto-generated by scripts/scrape.py (fast mode) */
window.MB_DATA = {
  product: "몽베스트 생수 2L x 12",
  lastUpdated: "2025-09-11T03:19:15.959203+09:00",
  sellers: [{'id': 'danawa', 'name': '다나와', 'url': 'https://prod.danawa.com/bridge/go_link_goods.php?cate_c1=46803&cate_c2=46819&cate_c3=56982&cate_c4=0&cmpny_c=TP40F&link_prod_c=I26514425892&keyword=%EB%AA%BD%EB%B2%A0%EC%8A%A4%ED%8A%B8+2L+12&r=17575283613309&cate=1623153', 'priceKRW': 5500, 'shippingKRW': 0, 'delivery': '일반'}]
};
