/* Auto-generated by scripts/scrape.py (or edit manually) */
window.MB_DATA = {
  product: "몽베스트 생수 2L x 12 (샘플)",
  lastUpdated: "2025-09-03T18:00:00+09:00",
  note: "샘플 데이터입니다. 실제 가격/링크로 교체하세요.",
  sellers: [
    { id: "coupang", name: "쿠팡", url: "https://www.coupang.com/", priceKRW: 11900, shippingKRW: 0, delivery: "로켓배송" },
    { id: "danawa", name: "다나와", url: "https://prod.danawa.com/", priceKRW: 12900, shippingKRW: 0, delivery: "일반택배" },
    { id: "naver", name: "네이버쇼핑", url: "https://search.shopping.naver.com/", priceKRW: 12500, shippingKRW: 2500, delivery: "스토어별" },
    { id: "gmarket", name: "G마켓", url: "https://www.gmarket.co.kr/", priceKRW: 11800, shippingKRW: 3000, delivery: "일반택배" },
    { id: "ssg", name: "SSG", url: "https://www.ssg.com/", priceKRW: 13900, shippingKRW: 0, delivery: "쓱배송" },
    { id: "11st", name: "11번가", url: "https://www.11st.co.kr/", priceKRW: 12100, shippingKRW: 3000, delivery: "일반택배" }
  ]
};
