/* Auto-generated by scripts/scrape.py */
window.MB_DATA = {
  product: "몽베스트 생수 2L x 12",
  lastUpdated: "2025-09-05T15:18:49.033318+09:00",
  sellers: [{'id': 'danawa', 'name': '다나와', 'url': 'https://prod.danawa.com/bridge/go_link_goods.php?cate_c1=46803&cate_c2=46819&cate_c3=56982&cate_c4=0&cmpny_c=TP40F&link_prod_c=V93361895770&keyword=%EB%AA%BD%EB%B2%A0%EC%8A%A4%ED%8A%B8+2L+12&r=17570531316492&cate=1623153', 'priceKRW': 8100, 'shippingKRW': 0, 'delivery': '일반'}]
};
