from datetime import datetime
from zoneinfo import ZoneInfo

# TODO: 실제 크롤링/공식 API 호출로 교체
# - requests + BeautifulSoup로 각 판매 페이지 파싱
# - 또는 제휴/공식 가격 API 사용 (권장)
# - 결과를 아래 sellers 리스트에 채워 넣기

sellers = [
    {"id":"coupang","name":"쿠팡","url":"https://www.coupang.com/","priceKRW":11900,"shippingKRW":0,"delivery":"로켓배송"},
    {"id":"danawa","name":"다나와","url":"https://prod.danawa.com/","priceKRW":12900,"shippingKRW":0,"delivery":"일반택배"},
    {"id":"naver","name":"네이버쇼핑","url":"https://search.shopping.naver.com/","priceKRW":12500,"shippingKRW":2500,"delivery":"스토어별"},
    {"id":"gmarket","name":"G마켓","url":"https://www.gmarket.co.kr/","priceKRW":11800,"shippingKRW":3000,"delivery":"일반택배"},
    {"id":"ssg","name":"SSG","url":"https://www.ssg.com/","priceKRW":13900,"shippingKRW":0,"delivery":"쓱배송"},
    {"id":"11st","name":"11번가","url":"https://www.11st.co.kr/","priceKRW":12100,"shippingKRW":3000,"delivery":"일반택배"},
]

kst = ZoneInfo("Asia/Seoul")
now = datetime.now(kst).isoformat()

content = f"""
/* Auto-generated by scripts/scrape.py */
window.MB_DATA = {{
  product: "몽베스트 생수 2L x 12",
  lastUpdated: "{now}",
  sellers: {sellers}
}};
""".strip() + "\n"

with open("prices.js", "w", encoding="utf-8") as f:
    f.write(content)

print("prices.js updated at", now)
